### ISSUE TITLE
Don't know how to start this

### ISSUE THREAD

**Issue by levi-l-damian** [vasilakisfil/rails_tutorial_ember#11]
I cloned the repo.
I executed: npm install and bower install.
The first one ended with some missing things i.e. missing: punycode@>=0.2.0, required by tough-cookie@0.12.1
and some invalids i.e.
invalid: debug@2.2.0 /Users/liviu-mac/ember_projects/rails_tutorial_ember/node_modules/ember-cli/node_modules/debug
Any attempt to execute ember build, or ember server, or ember test fails with the error: -bash: ember: command not found

I executed: npm install -g ember-cli
But now I am getting the error: could not find watchman

**Comment by vasilakisfil** [comment]
hmm let me try from my brand new fresh machine :P

**Comment by vasilakisfil** [comment]
@levi-l-damian which nodejs version do you have ?

**Comment by levi-l-damian** [comment]
$ node -v

v0.10.32

On Mon, Jun 8, 2015 at 6:06 PM, Filippos Vasilakis <notifications@github.com
> wrote:

> @levi-l-damian <https://github.com/levi-l-damian> which nodejs version do
> you have ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vasilakisfil/rails_tutorial_ember/issues/11#issuecomment-110156883>
> .
>



-- 
Levi

**Comment by levi-l-damian** [comment]
I upgraded node to this:
node -v
v0.12.4
Now the error when I am trying ember serve command is:
version: 0.2.7
Could not find watchman, falling back to NodeWatcher for file system events.
Visit http://www.ember-cli.com/#watchman for more info.
Cannot find module 'ember-cli/lib/broccoli/ember-app'
Error: Cannot find module 'ember-cli/lib/broccoli/ember-app'

**Comment by levi-l-damian** [comment]
I have a clean installation of node version 0.12.4
I can execute ember new my-new-app
followed by 
cd my-new-app
npm install && bower install
ember server

the server starts and using http://localhost:4200
I am getting in the browser the message welcome to Ember JS

Can't get the same results when I am using
git clone https://github.com/vasilakisfil/rails_tutorial_ember.git

Not sure what is the problem.

**Comment by vasilakisfil** [comment]
if you are still interested/still having problems take a look on the new tutorial: https://github.com/vasilakisfil/ember_on_rails5 (which depends on: https://github.com/vasilakisfil/rails5_api_tutorial )
