### ISSUE TITLE
Upgrade to Ember 2.x and ember-simple-auth 1.x

### ISSUE THREAD

**Issue by vzelenko** [vasilakisfil/rails_tutorial_ember#12]
It would be great to see an upgrade to the newer version of ember & simple auth components, as there has been quite a bit of change to both of them since this tutorial was released.

**Comment by vasilakisfil** [comment]
Unfortunately too busy at the moment but I am planning to release a new guide around ember 2, Rails 5 and JSONAPI towards the end of January.

**Comment by vzelenko** [comment]
Of course!  And THANK YOU for putting this amazing guide in the first place.  :)

**Comment by vasilakisfil** [comment]
Released: https://github.com/vasilakisfil/ember_on_rails5 (which depends on that: https://github.com/vasilakisfil/rails5_api_tutorial)
